#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED D5

#define MASTER_LEFT

#define FORCE_NKRO

#define TAPPING_TERM 200
#define QUICK_TAP_TERM 150

#define UNICODE_SELECTED_MODES UC_MAC

#define SPLIT_LED_STATE_ENABLE
#define SPLIT_OLED_ENABLE

#define OLED_FONT_H "keyboards/crkbd/lib/glcdfont.c"
